Traceback (most recent call last):
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ynorden/mambaforge/envs/siparcs/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import os                         
import xarray as xr 
import pandas as pd
import matplotlib                 
import matplotlib.pyplot as plt   
#plt.rcParams["figure.figsize"] = (9,6)  
import cartopy                  
import cartopy.crs as ccrs      
import plotly.express as px
import hvplot.xarray
import holoviews as hv
hv.extension('bokeh')
#hv.extension('plotly')
import numpy as np
import panel as pn
import panel.widgets as pnw
import ipywidgets as ipw
from sklearn import datasets, linear_model
from scipy import stats
from sklearn.metrics import mean_squared_error, r2_score
from pycurrents.system import Bunch
import glob2
import hvplot.pandas  # noqa
import hvplot.xarray  # noqa
import cartopy.crs as ccrs
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 22[0m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m [38;5;28;01mimport[39;00m stats
[1;32m     21[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m mean_squared_error, r2_score
[0;32m---> 22[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpycurrents[39;00m[38;5;21;01m.[39;00m[38;5;21;01msystem[39;00m [38;5;28;01mimport[39;00m Bunch
[1;32m     23[0m [38;5;28;01mimport[39;00m [38;5;21;01mglob2[39;00m
[1;32m     24[0m [38;5;28;01mimport[39;00m [38;5;21;01mhvplot[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpandas[39;00m  [38;5;66;03m# noqa[39;00m

[0;31mModuleNotFoundError[0m: No module named 'pycurrents'

